### ISSUE TITLE
I have this NUA tattooed on me

### ISSUE THREAD

**Issue by pinballelectronica** [johnsonjh/altoschat#2]
That is all!

**Comment by johnsonjh** [comment]
@pinballelectronica Thats actually awesome even if very few people would get it 👍🏻

**Comment by pinballelectronica** [comment]
I sent this to people I was doing things with back then and they didn't remember either ha.  there was another one not sure it altger but am hazy on the address.  I want to say 454 something.  anyway..
![nua](https://github.com/user-attachments/assets/bad84b33-b370-4699-8927-44e84eba817f)
